package com.immunology.logic.utils.enums;

public enum FormType {

	CLINICAL_MANIFESTATIONS_FORM, COMPLAINTS_FORM, DIAGNOSIS_VERIFICATION_DATA,
	INSTRUMENTAL_DATA, LABORATORY_DATA_FORM, MAIN_TREATMENT_DATA, MORPHOLOGICAL_DATA,
	PREVENTIVE_MEASURES_DATA, REHABILITATION_DATA
}
